### ISSUE TITLE
skip function

### ISSUE THREAD

**Issue by lmiq** [JuliaEarth/Variography.jl#82]
https://github.com/JuliaEarth/Variography.jl/blob/b1e401eb8514fad469d9514693412caf6f9cda9c/src/empirical.jl#L53

Continuing the discussion from Zulip:

Here I would prefer defining 

```julia
skip(::Type{VariogramAccumAlgo}, i::Int, j::Int) = ...
skip(::Type{OtherAlgo}, i::Int, j::Int) = ...
```

outside the function, to avoid the closure, and then just call `skip(VariogramAccumAlgo, i, j) && continue` inside the loop.

(I'm not sure if the custom definition of iterators apply easily, as I don't know what `neighbors` return)

**Comment by juliohm** [comment]
@lmiq the current approach is not capturing variables from scope, right? Just returning a lambda.

**Comment by juliohm** [comment]
Also, can we continue the discussion in #geostats.jl in Zulip? It is easier and more dynamic. These GitHub issues we use for actual issues, and centralize all of them in the GeoStats.jl repo instead of submodules.
